name: (📡) Verify

on:
  push:
    branches-ignore:
      - 'main'
  workflow_dispatch:

jobs:
  verify:
    uses: sitepark/github-project-workflow/.github/workflows/maven-verify.yml@main
    with:
      pre-build-script: sudo apt-get install -y libvips-tools

